-- MySQL Script generated by MySQL Workbench
-- Tue Feb  6 16:21:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema smart_coffee
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `smart_coffee` ;

-- -----------------------------------------------------
-- Schema smart_coffee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smart_coffee` DEFAULT CHARACTER SET utf8 ;
USE `smart_coffee` ;

-- -----------------------------------------------------
-- Table `smart_coffee`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_coffee`.`clients` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `coupon_code` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `coupon_code_UNIQUE` (`coupon_code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart_coffee`.`recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_coffee`.`recipes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `content` TEXT NOT NULL,
  `photo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart_coffee`.`ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_coffee`.`ingredients` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `preparation_time` INT NOT NULL,
  `photo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart_coffee`.`complements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_coffee`.`complements` (
  `recipe_id` INT UNSIGNED NOT NULL,
  `ingredient_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`recipe_id`, `ingredient_id`),
  INDEX `fk_ingredients_recipes_recipes_idx` (`recipe_id` ASC),
  INDEX `fk_ingredients_recipes_ingredients_idx` (`ingredient_id` ASC),
  CONSTRAINT `fk_ingredients_recipes_ingredients`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `smart_coffee`.`ingredients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredients_recipes_recipes`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `smart_coffee`.`recipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart_coffee`.`client_recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_coffee`.`client_recipes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `recipe_id` INT UNSIGNED NOT NULL,
  `client_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_items_recipes_idx` (`recipe_id` ASC),
  INDEX `fk_client_recipes_clients1_idx` (`client_id` ASC),
  CONSTRAINT `fk_orders_items_recipes`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `smart_coffee`.`recipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_recipes_clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `smart_coffee`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart_coffee`.`client_recipe_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_coffee`.`client_recipe_ingredients` (
  `ingredient_id` INT UNSIGNED NOT NULL,
  `client_recipe_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ingredient_id`, `client_recipe_id`),
  INDEX `fk_complements_ingredients_idx` (`ingredient_id` ASC),
  INDEX `fk_complements_orders_items_idx` (`client_recipe_id` ASC),
  CONSTRAINT `fk_complements_ingredients`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `smart_coffee`.`ingredients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_complements_orders_items`
    FOREIGN KEY (`client_recipe_id`)
    REFERENCES `smart_coffee`.`client_recipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smart_coffee`.`recipe_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_coffee`.`recipe_ingredients` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ingredient_id` INT UNSIGNED NOT NULL,
  `recipe_id` INT UNSIGNED NOT NULL,
  INDEX `fk_recipes_complements_recipes_idx` (`recipe_id` ASC),
  INDEX `fk_recipes_complements_ingredients_idx` (`ingredient_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ingredients_has_recipes_ingredients1`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `smart_coffee`.`ingredients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredients_has_recipes_recipes1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `smart_coffee`.`recipes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `smart_coffee`.`recipes`
-- Insert de receitas
-- -----------------------------------------------------
START TRANSACTION;
USE `smart_coffee`;
INSERT INTO `smart_coffee`.`recipes` (`name`, `content`, `photo`) VALUES ('Café duplo', '', 'images/cafe-duplo.svg');
INSERT INTO `smart_coffee`.`recipes` (`name`, `content`, `photo`) VALUES ('Café expresso', '', 'images/coffee.svg');
INSERT INTO `smart_coffee`.`recipes` (`name`, `content`, `photo`) VALUES ('Mocha', '', 'images/mocha.svg');
INSERT INTO `smart_coffee`.`recipes` (`name`, `content`, `photo`) VALUES ('Cappuccino', '', 'images/cappuccino.svg');
INSERT INTO `smart_coffee`.`recipes` (`name`, `content`, `photo`) VALUES ('Americano', '', 'images/cafe-americano.svg');

COMMIT;


-- -----------------------------------------------------
-- Data for table `smart_coffee`.`ingredients`
-- Insert de ingredientes
-- -----------------------------------------------------
START TRANSACTION;
USE `smart_coffee`;
INSERT INTO `smart_coffee`.`ingredients` (`name`, `preparation_time`, `photo`) VALUES ('Café', 45, 'images/grao-de-cafe.svg');
INSERT INTO `smart_coffee`.`ingredients` (`name`, `preparation_time`, `photo`) VALUES ('Açúcar', 10, 'images/acucar.svg');
INSERT INTO `smart_coffee`.`ingredients` (`name`, `preparation_time`, `photo`) VALUES ('Chocolate', 10, 'images/chocolate.svg');
INSERT INTO `smart_coffee`.`ingredients` (`name`, `preparation_time`, `photo`) VALUES ('Leite', 10, 'images/leite.svg');
INSERT INTO `smart_coffee`.`ingredients` (`name`, `preparation_time`, `photo`) VALUES ('Chantilly', 10, 'images/chantilly.svg');
INSERT INTO `smart_coffee`.`ingredients` (`name`, `preparation_time`, `photo`) VALUES ('Donuts - Super recheados', 45, 'images/donut.svg');
INSERT INTO `smart_coffee`.`ingredients` (`name`, `preparation_time`, `photo`) VALUES ('Cookie de Chocolate', 45, 'images/cookie.svg');
INSERT INTO `smart_coffee`.`ingredients` (`name`, `preparation_time`, `photo`) VALUES ('CupCake', 45, 'images/cupcake.svg');

COMMIT;


-- -----------------------------------------------------
-- Data for table `smart_coffee`.`complements`
-- Insert dos complementos disponíveis por receita
-- -----------------------------------------------------
START TRANSACTION;
USE `smart_coffee`;

-- Café Duplo
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (1, 2); -- Açúcar
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (1, 4); -- Leite
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (1, 5); -- Chantilly
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (1, 6); -- Donuts
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (1, 7); -- Cookie de Chocolate
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (1, 8); -- CupCake

-- Café Expresso
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (2, 2); -- Açúcar
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (2, 4); -- Leite
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (2, 5); -- Chantilly
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (2, 6); -- Donuts
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (2, 7); -- Cookie de Chocolate
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (2, 8); -- CupCake

-- Mocha
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (3, 2); -- Açúcar
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (3, 4); -- Leite
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (3, 5); -- Chantilly
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (3, 6); -- Donuts
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (3, 7); -- Cookie de Chocolate
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (3, 8); -- CupCake

-- Cappuccino
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (4, 2); -- Açúcar
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (4, 4); -- Leite
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (4, 5); -- Chantilly
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (4, 6); -- Donuts
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (4, 7); -- Cookie de Chocolate
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (4, 8); -- CupCake

-- Americano
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (5, 2); -- Açúcar
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (5, 4); -- Leite
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (5, 5); -- Chantilly
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (5, 6); -- Donuts
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (5, 7); -- Cookie de Chocolate
INSERT INTO `smart_coffee`.`complements` (`recipe_id`, `ingredient_id`) VALUES (5, 8); -- CupCake

COMMIT;


-- -----------------------------------------------------
-- Data for table `smart_coffee`.`recipe_ingredients`
-- Insert dos ingredientes das receitas
-- -----------------------------------------------------
START TRANSACTION;
USE `smart_coffee`;

-- Café duplo
INSERT INTO `smart_coffee`.`recipe_ingredients` (`recipe_id`, `ingredient_id`) VALUES (1, 1); -- Café

-- Café expresso
INSERT INTO `smart_coffee`.`recipe_ingredients` (`recipe_id`, `ingredient_id`) VALUES (2, 1); -- Café

-- Mocha
INSERT INTO `smart_coffee`.`recipe_ingredients` (`recipe_id`, `ingredient_id`) VALUES (3, 1); -- Café
INSERT INTO `smart_coffee`.`recipe_ingredients` (`recipe_id`, `ingredient_id`) VALUES (3, 3); -- Chocolate
INSERT INTO `smart_coffee`.`recipe_ingredients` (`recipe_id`, `ingredient_id`) VALUES (3, 4); -- Leite

-- Cappuccino
INSERT INTO `smart_coffee`.`recipe_ingredients` (`recipe_id`, `ingredient_id`) VALUES (4, 1); -- Café
INSERT INTO `smart_coffee`.`recipe_ingredients` (`recipe_id`, `ingredient_id`) VALUES (4, 3); -- Chocolate
INSERT INTO `smart_coffee`.`recipe_ingredients` (`recipe_id`, `ingredient_id`) VALUES (4, 4); -- Leite

-- Americano
INSERT INTO `smart_coffee`.`recipe_ingredients` (`recipe_id`, `ingredient_id`) VALUES (5, 1); -- Café

COMMIT;
